services:
    bdd:
        image: mysql
        container_name: mysql
        environment:
            - MYSQL_DATABASE=meliodas
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - curriculum:/var/lib/mysql
        networks:
            - curriculum
    # server:
    #     image: node:18
    #     container_name: API
    #     ports:
    #         - "5000:5000"
    #     working_dir: /app
    #     command: sh -c "npm run dev"
    #     environment:
    #         - NODE_ENV=dev
    #     volumes:
    #         - ./back:/app
    #     networks:
    #         - curriculum
    #     stop_grace_period: 1s
    client:
        image: node:20
        container_name: front
        ports:
            - "3000:3000"
        working_dir: /app
        command: sh -c "npm run dev"
        volumes:
            - ./front:/app
        networks:
            - curriculum
        stop_grace_period: 1s
    # admin:
    #     image: node:20
    #     container_name: admin
    #     ports:
    #         - "3001:5173"
    #     working_dir: /app
    #     command: sh -c "npm run dev"
    #     volumes:
    #         - ./admin:/app
    #     networks:
    #         - curriculum
    #     stop_grace_period: 1s
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=bdd
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - "8081:80"
        networks:
            - curriculum
networks:
    curriculum:
volumes:
    curriculum: {}
