services:
    bdd:
        image: mysql
        container_name: mysql
        environment:
            - MYSQL_DATABASE=meliodas
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - curriculum:/var/lib/mysql
        networks:
            - curriculum

    server:
        image: node:18
        container_name: API
        ports:
            - "5000:5000"
        working_dir: /server
        command: sh -c "npm install && npm run dev"
        environment:
            - NODE_ENV=dev
        volumes:
            - ./back:/back
        networks:
            - curriculum
        stop_grace_period: 1s

    client:
        image: httpd:alpine3.21
        container_name: vanilla
        ports:
            - "8080:80"
        working_dir: /front
        # volumes:
        #     - ./client:/client
        networks:
            - curriculum
        stop_grace_period: 1s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=bdd
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - "8081:80"
        networks:
            - curriculum
networks:
    curriculum:
volumes:
    curriculum: {}
